FROM node:20-alpine AS builder
WORKDIR /app
COPY package.json yarn.lock* ./
COPY packages ./packages
COPY apps/dashboard ./apps/dashboard
RUN yarn install
RUN yarn build
FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
EXPOSE 5173
CMD ["npm", "run", "preview"]
