FROM node:20-alpine

WORKDIR /app

# Kopiuj tsconfig z root
COPY tsconfig.json ./

WORKDIR /app/apps/core

# Kopiuj core app
COPY apps/core/package.json ./
COPY apps/core/src ./src
COPY apps/core/tsconfig.json ./

# Install + build
RUN npm install && npm run build

# Runtime image
FROM node:20-alpine
WORKDIR /app
COPY --from=0 /app/apps/core/node_modules ./node_modules
COPY --from=0 /app/apps/core/dist ./dist
COPY public ./public

EXPOSE 3000
CMD ["node", "/app/dist/main.js"]
