global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: unionai-core
    static_configs:
      - targets:
          - unionai-core.fly.dev:443
    scheme: https
    tls_config:
      insecure_skip_verify: false
    metrics_path: /metrics
    scrape_timeout: 10s
